app/ghabz/routes.py
import os
import jdatetime
from datetime import timedelta

from flask import Blueprint
from flask import render_template,request, jsonify
from .util import jalali_string_to_time
import sys
ghabz_bp = Blueprint('ghabz', __name__, template_folder='templates', static_folder='static', url_prefix='/ghabz')

@ghabz_bp.route('/')
def hello_world():  # put application's code here

    return render_template("Tel_Page.html")

@ghabz_bp.route('/chart')
def chart():

    return render_template("Chart_Page.html")


@ghabz_bp.route('/isAlive')
def isAlivePage():

    return render_template("Is_Alive.html")

def is_empty_dict(d):
    return d is None or not d  # Check if dictionary is None or empty


@ghabz_bp.post('/choose water')
def calculate_meter():
    print(request.form.keys())
    for k in request.form.keys():
        print(request.form.get(k))

    return render_template("Tel_Page.html")

@ghabz_bp.get('/test_sidebar')
def test_sidebar():
    return render_template("sidebar_tst.html")
# from tb_rest_client.rest_client_ce import Tenant
# @ghabz_bp.route('/create_tenant/<tenant_name>')
# def create_tenant(tenant_name):
#     rest_client = RestClientCE(base_url="*")
#     rest_client.login(username="*", password="*")
#     tenant = Tenant(title=tenant_name, name=tenant_name, email="example@example.com")
#     rest_client.save_tenant(tenant)
#     return 'done'

from .APITB import wholeKeeeper,  base_url, username, password, RestClientCE, decor_get_nearest_time_epoch, get_device_entity_by_name
@ghabz_bp.post('/get_meter_name_API')
def get_meter_name_API():
    meter_kind = request.form.get('meterKind')
    return jsonify(wholeKeeeper[meter_kind])

meter_data_return_dict ={'error-start-time': None}
all_meter_data_return_dict ={'error-start-time': None}
@ghabz_bp.post('/get_meter_data_API')
def get_meter_data_API():

    # gather form data returned from js fetch API
    meter_kind = request.form.get('meterKind')
    meter_name = request.form.get('meterName')
    start_time = request.form.get('startTime')
    stop_time = request.form.get('endTime')
    clk_EN = request.form.get('clkEN')
    if (str(clk_EN)  == 'true'):
        clk_EN = True
    else:
        clk_EN = False
    start_clock = request.form.get('startClock')
    stop_clock = request.form.get('stopClock')
    print(meter_name,meter_kind,start_time,stop_time,clk_EN,start_clock,stop_clock)

    # TODO: add some data to say if we can access to API else return error to service in front
    # login to API
    rest_client = RestClientCE(base_url=base_url)
    rest_client.login(username=username, password=password)

    # get data from DB
    meter_kind_approved= wholeKeeeper.get(meter_kind)

    # meter kind field checking
    if meter_kind_approved:
        meter_data_return_dict.update({'error-meter-kind': None})
    else:
        # meter_data_return_dict.update({'error-meter-kind': 'این نوع دیوایس وجود ندارد.'})
        meter_data_return_dict.update({'error-meter-kind': True})


    # print('here')
    #meter name fileld checking
    meter_name_approved = None
    meter_data_return_dict.update({'error-meter-name': None})
    if  meter_kind_approved:
        meter_name_approved = meter_kind_approved.get(meter_name)
        if not meter_name_approved:
            # meter_data_return_dict.update({'error-meter-name': 'دیوایسی با این نام وجود ندارد.'})
            meter_data_return_dict.update({'error-meter-name': True})


    # see if the device is alive
    isAlive = False

    meter_data_return_dict.update({'isAlive': isAlive})
    if meter_name_approved:
        print(meter_name_approved[1])
        # isAlive = get_device_alive(restClient=rest_client, deviceName=meter_name_approved[1])
        # meter_data_return_dict.update({'isAlive':isAlive})
        # print('checking is alive', meter_data_return_dict)

    meter_data_return_dict.update({'error-start-clock': False})
    meter_data_return_dict.update({'error-stop-clock': False})
    raisedStartEpoch = 0
    raisedStopEpoch = 0
    if clk_EN == True:
        print("in here to ask clock valid" )
        colonOcurrClockStart = str(start_clock).count(':')
        colonOcurrClockStop = str(stop_clock).count(':')
        if colonOcurrClockStart == 1:
            startClockList = str(start_clock).split(':')
            try:
                raisedStartEpoch = (int(startClockList[0]) * 60 + int(startClockList[1])) * 60
                print(raisedStartEpoch)
            except:
                meter_data_return_dict.update({'error-start-clock': True})
        else:
            meter_data_return_dict.update({'error-start-clock': True})

        if colonOcurrClockStop == 1:
            stopClockList = str(stop_clock).split(':')
            try:
                raisedStopEpoch = (int(stopClockList[0]) * 60 + int(stopClockList[1])) * 60
                print(raisedStopEpoch)
            except:
                meter_data_return_dict.update({'error-stop-clock': True})
        else:
            meter_data_return_dict.update({'error-stop-clock': True})


    # see if the Dates are valid
    start_epoch, start_date_obj = jalali_string_to_time(start_time)
    stop_epoch, stop_date_obj = jalali_string_to_time(stop_time)


    print('start epoch bef:', start_epoch)
    if not start_epoch == None:
        start_epoch = start_epoch + raisedStartEpoch
        if sys.platform.startswith('linux'):
            start_epoch = start_epoch - (3 * 60 + 30) * 60

    if not stop_epoch == None:
        stop_epoch = stop_epoch + raisedStopEpoch
        if sys.platform.startswith('linux'):
            stop_epoch = stop_epoch - (3 * 60 + 30) * 60

    print('start epoch aft:', start_epoch)

    print('epoch:' ,start_epoch)
    meter_data_return_dict.update({'error-start-time': None})
    if start_epoch == None:
        # meter_data_return_dict.update({'error-start-time': 'فرمت تاریخ ابتدا صحیح نیست'})
        meter_data_return_dict.update({'error-start-time': True})

    meter_data_return_dict.update({'error-stop-time': None})
    if stop_epoch == None:
        # meter_data_return_dict.update({'error-stop-time': 'فرمت تاریخ انتها صحیح نیست'})
        meter_data_return_dict.update({'error-stop-time': True})

    meter_data_return_dict.update({'error-time-seq': None})
    time_approved = False
    if ( not start_epoch == None) and ( not stop_epoch == None):
        if (start_epoch > stop_epoch):
            print(start_epoch, stop_epoch, )
            # meter_data_return_dict.update({'error-time': 'تاریخ ابتدا جلوتر از تاریخ انتها است.'})
            meter_data_return_dict.update({'error-time-seq': True})
        else:
            time_approved = True

    # start to query
    data = {'available': False}
    meter_data_return_dict.update({'error-time-start-avlbl': None})
    meter_data_return_dict.update({'error-time-stop-avlbl': None})

    if (not meter_kind_approved == None)\
            and (not meter_name_approved == None)\
            and (time_approved == True):

        #get nearest data to start epoch
        from .APITB import epochDistanceToCheck, maxBoundaryTSRetry

        if clk_EN == True:
            epochDistanceToCheck = 1  # 1 minutes each query
            maxBoundaryTSRetry = .1  # .1*60 = 6 minutes

        print('maxBoundaryTSRetry, ',epochDistanceToCheck, maxBoundaryTSRetry)

        time_in_data_available_start = decor_get_nearest_time_epoch(restClient=rest_client,
                                                                    deviceName=meter_name_approved[1],
                                                                    date=start_epoch,  # TODO: change it to string time or other functions
                                                                    key_to_ask_for_nearest=meter_name_approved[2],
                                                                    from_epoch=True,
                                                                    epochDistanceToCheckInner=epochDistanceToCheck,
                                                                    maxBoundaryTSRetryInner=maxBoundaryTSRetry)
        print('time_in_data_available_start is : ',time_in_data_available_start)
        print('start_epoch is : ',start_epoch)
        print('stop_epoch is : ', stop_epoch)

        if time_in_data_available_start == 0:
            meter_data_return_dict.update({'error-time-start-avlbl': True})

        # get nearest data to stop epoch
        time_in_data_available_stop = decor_get_nearest_time_epoch(restClient=rest_client,
                                                                    deviceName=meter_name_approved[1],
                                                                    date=stop_epoch,  # TODO: change it to string time or other functions
                                                                    key_to_ask_for_nearest=meter_name_approved[2],
                                                                    from_epoch=True,
                                                                    epochDistanceToCheckInner=epochDistanceToCheck,
                                                                    maxBoundaryTSRetryInner=maxBoundaryTSRetry)
        if time_in_data_available_stop == 0:
            meter_data_return_dict.update({'error-time-stop-avlbl': True})

        print('here', meter_data_return_dict)
        deviceEntity = get_device_entity_by_name(restClient=rest_client, deviceName=meter_name_approved[1])

        if (not time_in_data_available_stop == 0) and (
        not time_in_data_available_start == 0):  # check if data is available in such epochs
            data_start = rest_client.get_timeseries(entity_id=deviceEntity, keys=meter_name_approved[2],
                                                    start_ts=time_in_data_available_start - 1,
                                                    end_ts=time_in_data_available_start + 1)
            print(rest_client)
            print('lets see the data_start: ', data_start)

app/ghabz/templates/ABI_NEGAR_TEMPLATE.html
<!DOCTYPE html>
<html lang="en">
<head>

<link rel="icon" type="image/x-icon" href={{ url_for('ghabz.static', filename="/images/favicon.ico") }}>
<title>{% block title %}{% endblock %}_ آبی نگار</title>
<meta charset="UTF-8">

<!--jquery v1 CDN-->
{#for persian cllender#}
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<!--jquery v1 CDN end-->

<!-- bootstrap CDN -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<!-- bootstrap CDN end -->

<!--font link nastaligh-->
<link rel="preconnect" href="//fdn.fontcdn.ir">
<link rel="preconnect" href="//v1.fontapi.ir">
<link href="https://v1.fontapi.ir/css/IranNastaliq" rel="stylesheet">
<link href="https://v1.fontapi.ir/css/Lotus" rel="stylesheet">
<!--font link nastaligh end-->

<link rel="stylesheet" href="{{ url_for('ghabz.static', filename='css/style.css') }}">

{% block style %}{% endblock %}
</head>
<body>


<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom navbar-light ">
  <div class="container-fluid">

    <a class="navbar-brand centered-navbar-brand font-nastaligh" href="https://abinegar.com">سامانه گزارش مصرف آبی نگار</a>

    <a class="navbar-brand" href="https://abinegar.com">
    <img src={{ url_for("ghabz.static", filename="/images/cropped-logo1.jpg") }} alt="Bootstrap" width="90" height="60">
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav" >
      <ul class="navbar-nav nav-tabs custom-nav-tabs ms-auto flex-row-reverse w-100">
        <li class="nav-item">
          <a class="nav-link" id="nav-ghabz" aria-current="page" href="{{ url_for('ghabz.hello_world') }}" >قبض</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="nav-chart" href="{{ url_for('ghabz.chart') }}" >نمودار</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="nav-alive" href="{{ url_for('ghabz.isAlivePage') }}" >کنتورهای فعال</a>
        </li>

      </ul>
    </div>
  </div>
</nav>



{% block form %}
{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% block jsScript %}
{% endblock %}
</body>
</html>

app/ghabz/templates/Is_Alive.html
{% extends "sidebar_tst.html" %}
{% block title %}کنتور های فعال{% endblock %}


{% block form %}
    <form>
        <div class="formContainer">
            <select name="meter_kind_selection" id="meter_kind_selection" class="meterSelect form-select font-nazanin" aria-label="Default select example" autofocus="true">
                <option selected value="None">نوع کنتور را انتخاب کنید</option>
                <option value="water">آب</option>
                <option value="electricity">برق</option>
                <option value="gas" disabled=true>گاز</option>
            </select>
            <div class="d-flex justify-content-center">
              <button type="button" class="btn btn-primary" id="submit-butt">
                  <span>Submit</span>
              </button>  {# never use type="submit" when using fetch API#}
            </div>

            <div class="d-flex justify-content-center">
                  <button type="button" class="btn btn-primary" id="spinner" hidden="true" disabled="true">
                      <span class="spinner-grow spinner-border" ></span>
                  </button>  {# never use type="submit" when using fetch API #}

                </div>

        </div>


        <select name="meter_place_selection" id="meter_place_selection" class="form-select centered-form-object font-nazanin" aria-label="Default select example" disabled="true" hidden="true">
            <option selected value="None">محل کنتور را انتخاب کنید</option>
          </select>

    </form>

    <div id="error-division" class="error-div font-nazanin">

    </div>

    <div class="deviceContainer font-nazanin" id="deviceContainer">
        <!-- Devices will be generated here -->
        </div>


        <script>const meter_name_API_url = "{{ url_for('ghabz.get_meter_name_API') }}"</script>
        <script>const get_all_isAlive_data_API_url = "{{ url_for('ghabz.get_all_isAlive_data_API') }}"</script>
         <script type="text/javascript" src="{{ url_for('ghabz.static', filename='js/Is_Alive.js') }}"></script>

{% endblock %}

app/ghabz/templates/Tel_Page.html
{% extends "sidebar_tst.html" %}
{% block title %}ارائه قبض {% endblock %}
{% block style %}

<!--persian callender-->
{#    https://github.com/behzadi/persianDatepicker#}
    <link type="text/css" rel="stylesheet" href="{{ url_for('ghabz.static', filename='css/persianDatepicker.css') }}" />
<!--persian callender end-->

<!--clock picker-->
    {#<script type="text/javascript" src="{{ url_for('ghabz.static', filename='js/jquery-clock-timepicker.min.js') }}"></script>#}
    {#<script type="text/javascript">#}
    {#$(document).ready(function() {#}
    {#    $('.precisionTime5').clockTimePicker({precision: 5});});#}
    {##}
    {#</script>#}
<!--clock picker end-->

<!--font awsome cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!--font awsome cdn end -->
<!-- clockpicker css -->

{% endblock %}

{%  block jsScript %}

<!--persian callender js -->
        <script type="text/javascript" src="{{ url_for('ghabz.static', filename='js/persianDatepicker.min.js') }}"></script>
    <script type="text/javascript">
    $(function() {
        $("#telemetry_stop_date, #span1").persianDatepicker();
    });

    $(function() {
        $("#telemetry_start_date, #span2").persianDatepicker();
    });
    </script>
<!--persian callender js end-->

<!-- clockpicker js -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.11.11/dayjs.min.js"></script>
    <script type="text/javascript" src="{{ url_for('ghabz.static', filename='js/timepicker-bs4.js')}}" defer="defer"></script>
    <script type="text/javascript">
{#    jQuery('#start_clock').timepicker({#}
{#    format: 'hh:mm A',#}
{#    });#}
{##}
{#    jQuery('#stop_clock').timepicker({#}
{#    format: 'hh:mm A',#}
{#    });#}

    jQuery('input.timepicker-bs4').timepicker;
    </script>


<!-- clockpicker js end-->
{% endblock %}

{% block form %}

<!-- form -->
{#    <div class="form-itself" >#}
        <form> {#action="/calculate_meter" method="post" >#}

          <select name="meter_kind_selection" id="meter_kind_selection" class="form-select centered-form-object font-nazanin" aria-label="Default select example" autofocus="true">
          <option selected value="None">نوع کنتور را انتخاب کنید</option>
          <option value="water">آب</option>
          <option value="electricity">برق</option>
          <option value="gas" disabled=true>گاز</option>
            </select>
          <div class="form-check form-switch centered-checkbox-object checkbox-num-two font-nazanin">
              <input class="form-check-input" type="checkbox" value="" id="singlechoosingCheckBox">
              <label class="form-check-label" for="singlechoosingBox">
                فعال نمودن تک به تک
              </label>
          </div>

          <div class="form-check form-switch centered-checkbox-object font-nazanin">
              <input class="form-check-input" type="checkbox" value="" id="clockCheckBox">
              <label class="form-check-label" for="clockCheckBox">
                فعال نمودن ساعت
              </label>
          </div>


          <select name="meter_place_selection" id="meter_place_selection" class="form-select centered-form-object font-nazanin" aria-label="Default select example" disabled="true" >
            <option selected value="None">محل کنتور را انتخاب کنید</option>
          </select>


          <div class="mb-3 centered-form-object font-nazanin">
            <label for="telemetry_start_date" class="form-label">تاریخ ابتدا</label>
              <input name="start-date" type="text" class="form-control centered-text" id="telemetry_start_date" aria-describedby="start_data" placeholder="yyyy/mm/dd" autocomplete="off"/>
              <span id="span2" align="center"></span>
              <div id="start_data" class="form-text">تا ساعت 12 نیمه شب </div>
          </div>

          <div class="mb-3 centered-form-object font-nazanin" id="divStartClock">
            <label for="telemetry_start_clock" class="form-label">ساعت ابتدا</label>
              <input name="start_clock" type="time" class="form-control centered-text" id="telemetry_start_clock" aria-describedby="start_clock" autocomplete="off"/>
              <div id="start_clock" class="form-text"></div>
          </div>

          <div class="mb-3 centered-form-object font-nazanin">
            <label for="telemetry_stop_date" class="form-label">تاریخ انتها</label>
              <input name="stop-date" type="text" class="form-control centered-text" id="telemetry_stop_date" aria-describedby="stop_data" placeholder="yyyy/mm/dd" autocomplete="off"/>
              <span id="span1" align="center"></span>
              <div id="stop_data" class="form-text">تا ساعت 12 نیمه شب </div>
          </div>

          <div class="mb-3 centered-form-object font-nazanin" id="divStopClock">
            <label for="telemetry_stop_clock" class="form-label">ساعت انتها</label>
              <input name="stop_clock" type="time" class="form-control centered-text" id="telemetry_stop_clock" aria-describedby="stop_clock" autocomplete="off"/>
              <div id="stop_clock" class="form-text"></div>
          </div>

            <div class="d-flex justify-content-center">
              <button type="button" class="btn btn-primary" id="submit-butt">
                  <span>Submit</span>
              </button>  {# never use type="submit" when using fetch API #}
            </div>

            <div class="d-flex justify-content-center">
              <button type="button" class="btn btn-primary" id="spinner" hidden="true" disabled="true">
                  <span class="spinner-grow spinner-border" ></span>
              </button>  {# never use type="submit" when using fetch API #}

            </div>
        </form>
        <!--form-end-->

        <div id="data-div" class="font-nazanin">

            </div>

        <div id="error-division" class="error-div font-nazanin">

        </div>

        <div id="error-start-time-division" class="error-div font-nazanin">

            </div>
        <div id="error-stop-time-division" class="error-div font-nazanin">

            </div>

        <div id="my-table-for-all">
            <table class="table table-striped" >
                <thead id="all_meter_places_table">
                  <tr  class="bg-info">

                    <th scope="col" class="font-nazanin">محل کنتور</th>
                    <th scope="col" class="font-nazanin" id="heading2"> </th>  {# heading2 will fill with unit #}
                  </tr>
                </thead>
                <tbody  id="all_meter_places_table2">

                </tbody>
            </table>
        </div>
{#chart#}
        <div id="chart-container">
            <canvas id="myLineChart" class="chart-canvas"></canvas>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        <script src="scripts.js"></script>
{#if you dont need any charts in the website delete or comment the part above#}

        <script>const meter_name_API_url = "{{ url_for('ghabz.get_meter_name_API') }}"</script>
        <script>const get_meter_data_API_url = "{{ url_for('ghabz.get_meter_data_API') }}"</script>
        <script>const get_all_meter_data_API_url = "{{ url_for('ghabz.get_all_meter_data_API') }}"</script>
        <script type="text/javascript" src="{{ url_for('ghabz.static', filename='js/Tel_Page.js') }}"></script>
{% endblock %} {# form #}

app/ghabz/templates/TeleStatus.html
{% extends "ABI_NEGAR_TEMPLATE.html" %}

app/ghabz/templates/sidebar_tst.html
<!DOCTYPE html>
<html lang="en">
<head>

<link rel="icon" type="image/x-icon" href={{ url_for('ghabz.static', filename="/images/favicon.ico") }}>
<title>{% block title %}{% endblock %}_ آبی نگار</title>
<meta charset="UTF-8">

<!--jquery v1 CDN-->
{#for persian cllender#}
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<!--jquery v1 CDN end-->

<!-- bootstrap CDN -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<!-- bootstrap CDN end -->

<!--font link nastaligh-->
<link rel="preconnect" href="//fdn.fontcdn.ir">
<link rel="preconnect" href="//v1.fontapi.ir">
<link href="https://v1.fontapi.ir/css/IranNastaliq" rel="stylesheet">
<link href="https://v1.fontapi.ir/css/Lotus" rel="stylesheet">
<!--font link nastaligh end-->

<link rel="stylesheet" href="{{ url_for('ghabz.static', filename='css/style.css') }}">

{% block style %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-default fixed-top" style="background-color: #305680; position: sticky">
        <div  style="padding-top: 1rem;">
            <div class="navbar-text centered-navbar-brand">
                <a class="font-nastaligh" href="https://abinegar.com" style=" color: white; text-decoration: none;">سامانه گزارش مصرف دانشگاه صنعتی امیرکبیر</a>
            </div>

            <a class="navbar-brand" href="https://abinegar.com" style="margin-inline:auto; ">
                <img src={{ url_for("ghabz.static", filename="/images/thingsware White.png") }} width= 18%;>
                </a>

{#            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">#}
{#                <span class="navbar-toggler-icon"></span>#}
{#            </button>#}
{##}
{#                <div class="collapse navbar-collapse" id="navbarNav" >#}
{#                    <ul class="navbar-nav nav-tabs custom-nav-tabs ms-auto flex-row-reverse w-100">#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" id="nav-ghabz" aria-current="page" href="{{ url_for('ghabz.hello_world') }}" >قبض</a>#}
{#                            </li>#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" id="nav-chart" href="{{ url_for('ghabz.chart') }}" >نمودار</a>#}
{#                            </li>#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" id="nav-alive" href="{{ url_for('ghabz.isAlivePage') }}" >کنتورهای فعال</a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
            </div>
        </nav>

    <div id="contentBox" style="float: left; margin-right:0px; height: 100%; width:15%; margin-bottom:0; background-color: #305680; text-align: center; color: white; font-family: Lotus, sans-serif; font-size: 1.5rem; position: fixed;">

     <!-- columns divs, float left, no margin so there is no space between column, width=1/3 -->

        <div id="column1" style="  width:100%; border-bottom: 1px solid wheat; padding-bottom: .5rem; padding-top: .5rem; border-top: 1px solid wheat">
            <a class="nav-link" id="nav-ghabz" aria-current="page" href="{{ url_for('ghabz.hello_world') }}" >گزارش مصرف</a>
        </div>

        <div id="column2" style=" width:100%; border-bottom: 1px solid wheat; margin-top: 0.5rem; padding-bottom: .5rem; ">
            <a class="nav-link" id="nav-chart" href="{{ url_for('ghabz.chart') }}" >نمودار</a>
        </div>

        <div id="column3" style=" width:100%; border-bottom: 1px solid wheat; margin-top: 0.5rem; padding-bottom: .5rem; ">
            <a class="nav-link" id="nav-alive" href="{{ url_for('ghabz.isAlivePage') }}" >کنتورهای فعال</a>
        </div>


        <div id="column4" style=" width:100%; border-top: 1px solid aqua; margin-bottom: 0; padding-top: .25rem; bottom: 5rem;  position:absolute ">
            v 0.4.0
        </div>

        </div>

    <div style="margin-left: 15%">
        {% block form %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    {% block jsScript %}
    {% endblock %}

    <div style="position: fixed; bottom: 0px; right: 10px; color: darkblue; text-align: center">
        <div>
        Metering Report
            </div>
        <div>
        v 0.4.0
            </div>
        <div>
        Abinegar Co.
            </div>
    </div>
    </body>